### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by jiaotiliu** [shurco/litecart#14]

**Comment by shurco** [comment]
Hi,
In the near future, I will release the first version and include a description.

**Comment by bgsnwhh** [comment]
I hope the faster the better, and I look forward to your tutorial

**Comment by jiaotiliu** [comment]
> Hi, In the near future, I will release the first version and include a description.

The faster the better, I will test it as soon as possible!

**Comment by jiaotiliu** [comment]
> Hi, In the near future, I will release the first version and include a description.

Can this cart support digital delivery?For example,Some buy a key,and we can send the key by email.Also,if can pay with usdt,it will be great.

**Comment by shurco** [comment]
> Can this cart support digital delivery?For example,Some buy a key,and we can send the key by email.Also,if can pay with usdt,it will be great.

1. I plan to implement digital delivery in the near future.
2. Integrating crypto payment will not be difficult if the payment system supports it. Currently, only Stripe is supported, but I may consider adding support for other payment systems in the future.

**Comment by jiaotiliu** [comment]
Thats great,by the way,when the first release avaivable?Is there a specific schedule here?

**Comment by jiaotiliu** [comment]
> 


Thats great,by the way,when the first release avaivable?Is there a specific schedule here?

**Comment by shurco** [comment]
> Thats great,by the way,when the first release avaivable?Is there a specific schedule here?

https://github.com/shurco/litecart/issues/21#issuecomment-1707843963

**Comment by jiaotiliu** [comment]
> Hi, In the near future, I will release the first version and include a description.

I see there has been a release v0.1.1

Is there have a install guide or description?

**Comment by shurco** [comment]
I drafted a small documentation.
https://github.com/shurco/litecart/blob/main/README.md#installation
