### ISSUE TITLE
🤗 [Question]: Custom modification

### ISSUE THREAD

**Issue by inna-ip** [shurco/litecart#143]
### Question Description

Thank you for the project. It's great that it's free.
I need to add specific functionality - can I reach out to you for help?

### Checklist:

- [X] I agree to follow litecart's [Code of Conduct](https://github.com/shurco/litecart/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by shurco** [comment]
Yes. Please contact me through LinkedIn private messages.
