### ISSUE TITLE
🐛 [Bug]: Error running litecart for the first time

### ISSUE THREAD

**Issue by chr15m** [shurco/litecart#148]
### Bug Description

After `init` and `serve` and visiting localhost:8000 I saw a blank page and the following in the developer console of my browser:
```
21:45:04.189 Uncaught Error: Extension Error: The validator 'all' must be a function.
    Zn http://localhost:8080/_/assets/vee-validate-usGg8cAm.js:5
    $t http://localhost:8080/_/assets/vee-validate-usGg8cAm.js:5
    <anonymous> http://localhost:8080/_/assets/index-BETTTWNd.js:2
    <anonymous> http://localhost:8080/_/assets/index-BETTTWNd.js:2
```

### How to Reproduce

- Downloaded the litecart binary for my platform.
- Ran `litecart init` and it created the dirs.
- Ran `litecart serve` and it ran successfully.
- Then I tried to visit localhost:8080 and I was met with a blank page.
- I looked at the web developer console and saw the error.

### Expected Behavior

Litecart should start and present me with the first page.

### litecart Version

litecart version LiteCart v0.1.11 (453b7e4) from 2024-07-07

### Checklist:

- [X] I agree to follow litecart's [Code of Conduct](https://github.com/shurco/litecart/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by shurco** [comment]
Hi @chr15m
I rolled out a new version ([v0.1.12](https://github.com/shurco/litecart/releases)) where this issue has been fixed. Thanks for the fix @kaichaosun (https://github.com/shurco/litecart/commit/0f36efc8a46da6d9a72afafcb346ab9ff038de69)

**Comment by chr15m** [comment]
Fixed, thanks.
