### ISSUE TITLE
🚀 [Feature]: Support for shared hosting service 

### ISSUE THREAD

**Issue by abddayan** [shurco/litecart#155]
### Feature Description

Hi, can you consider making a pre compiled version ready to install on a Shared hosting service, please? I need an elegant solution like this for my clients on shared hosting. Doing that would greatly help.Thanks.

**Comment by shurco** [comment]
I am afraid that **litecart** cannot be installed on shared hosting. The fact is that this type of hosting does not allow the installation or running of third-party software, except for what is permitted by the hosting provider.
**Litecart** works perfectly on a simple and cheapest VPS.

**Comment by abddayan** [comment]
Alright. Thanks.
