### ISSUE TITLE
when the first release avaivable?Is there a specific schedule here?🤗 [Question]: 

### ISSUE THREAD

**Issue by bgsnwhh** [shurco/litecart#21]
### Question Description

when the first release avaivable?Is there a specific schedule here?

**Comment by shurco** [comment]
I am developing this project in my free time from work. I plan to release the release next week.

**Comment by jiaotiliu** [comment]
> I am developing this project in my free time from work. I plan to release first working version next week.

Thats great,I will try it as soon as possible when it released
