### ISSUE TITLE
🚀 [Feature]: Support for payment using cryptocurrency

### ISSUE THREAD

**Issue by shurco** [shurco/litecart#50]

**Comment by jiaotiliu** [comment]
This one's desperately needed.

**Comment by shurco** [comment]
> This one's desperately needed.

The solution has been found, the development process has begun.

**Comment by jiaotiliu** [comment]
> > 这个是迫切需要的。
> 
> 解决方案已经找到，开发过程已经开始。

Thats great!!

**Comment by shurco** [comment]
@jiaotiliu 
https://github.com/shurco/litecart#spectrocoin
