### ISSUE TITLE
🚀 [Feature]: WebHook support

### ISSUE THREAD

**Issue by shurco** [shurco/litecart#51]

**Comment by msalbrain** [comment]
Hey man 
Been looking for a project to contribute to, hope I can start with this. If yes could you give more explanation

**Comment by shurco** [comment]
> Hey man
> Been looking for a project to contribute to, hope I can start with this. If yes could you give more explanation

I planned to add webhook support for the shopping cart:
- payment initiation (sends a list of items in the cart to be paid)
- successful payment (sends brief information from the payment system, payment system name, cart ID)
- payment error (sends brief information from the payment system, payment system name, cart ID)
- payment refusal (payment system name, cart ID)

Also, it is necessary to add settings in the admin panel for where to send the webhook and under what conditions.

**Comment by msalbrain** [comment]
on it

**Comment by coderofsalvation** [comment]
Are there a latest beta builds (from github actions) which I can test?
I tried building the latest version, but somehow yarn errored (and I'm not really sure what I'm doing)

**Comment by shurco** [comment]
> Are there a latest beta builds (from github actions) which I can test? I tried building the latest version, but somehow yarn errored (and I'm not really sure what I'm doing)

Hi,  
Please create a new ticket and describe step by step what you did.  
Also, please specify which platform you tried (arm or x86) and the operating system.

**Comment by coderofsalvation** [comment]
thanks for the reply, but that was not my question.
I guess my question is: what do you think about adjusting the github action
so that it always produces build artifacts on master? giving people access
to latest beta versions (instead of releases, which date from 30th of july)

**Comment by shurco** [comment]
I'll think about it
