### ISSUE TITLE
🤗 [Question]:  building locally

### ISSUE THREAD

**Issue by c-nv-s** [shurco/litecart#64]
### Question Description

please can you add instructions for building locally
this will help those who wish to contribute to the project
I believe ``npm install yarn``, ``yarn add vite`` and ``yarn build`` are at least required

### Checklist:

- [X] I agree to follow litecart's [Code of Conduct](https://github.com/shurco/litecart/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by shurco** [comment]
Hello,  
I've added a brief instruction on how to run this locally:   
https://github.com/shurco/litecart#for-developers
