### ISSUE TITLE
🐛 [Bug]: ERROR:failed to render: render: template index does not exist

### ISSUE THREAD

**Issue by jiaotiliu** [shurco/litecart#67]
### Bug Description

![image](https://github.com/shurco/litecart/assets/134895892/9c09ecf8-e4e4-4e92-a967-51ecad8d743d)

I can access Admin UI,but when I setted up,I cant access Cart UI

### How to Reproduce

I build it with docker
error log
2023/11/22 10:31:54 | stdout | {"level":"error","latency":"332.804µs","status":500,"method":"GET","url":"/","error":"failed to render: render: template index does not exist","time":"2023-11-22T02:31:54Z","message":"Server error"}

### Expected Behavior

Cant access Cart UI

### litecart Version

v0.1.5

### Checklist:

- [X] I agree to follow litecart's [Code of Conduct](https://github.com/shurco/litecart/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by shurco** [comment]
Have you updated or is this the first installation?

**Comment by jiaotiliu** [comment]
> Have you updated or is this the first installation?

This is my first installation

**Comment by jiaotiliu** [comment]
> Have you updated or is this the first installation?

I reinstall litecart(v0.1.6),the UI is work.but Spectrocoin pay method still not  work.
`<html>
<body>

date | stream | content
-- | -- | --
2023/11/23 10:52:50 | stdout | {"level":"warn","latency":"987.676µs","status":400,"method":"POST","url":"/cart/payment","time":"2023-11-23T02:52:50Z","message":"Client error"}
2023/11/23 10:52:41 | stdout | {"level":"info","latency":"568.16µs","status":200,"method":"GET","url":"/api/_/settings/spectrocoin","time":"2023-11-23T02:52:41Z","message":"Success"}


</body>
</html>`

**Comment by shurco** [comment]
Did you do everything according to the [instructions](https://github.com/shurco/litecart#spectrocoin)? 
All fields with settings are required to be filled out!

**Comment by jiaotiliu** [comment]
Yes,I have setted up it
![image](https://github.com/shurco/litecart/assets/134895892/d5a68e92-bd5c-44e9-b318-7cd83f8ccc7d)

**Comment by jiaotiliu** [comment]
May be only Stripe and Spectrocoin payment method all setted,the Payment system can work?

**Comment by shurco** [comment]
> May be only Stripe and Spectrocoin payment method all setted,the Payment system can work?

This doesn't depend on it. You apparently have an internal error. I tried to deploy a new project, created a new merchant in Spectrocoin and everything worked for me. I'll think about how to catch your error.

**Comment by jiaotiliu** [comment]
> > May be only Stripe and Spectrocoin payment method all setted,the Payment system can work?
> 
> This doesn't depend on it. You apparently have an internal error. I tried to deploy a new project, created a new merchant in Spectrocoin and everything worked for me. I'll think about how to catch your error.

Is it possible that the reason behind my utilization of Docker to deploy LiteCart on Synology's DiskStation and accessing the website via Cloudflare Tunnel?

**Comment by jiaotiliu** [comment]
> > May be only Stripe and Spectrocoin payment method all setted,the Payment system can work?
> 
> This doesn't depend on it. You apparently have an internal error. I tried to deploy a new project, created a new merchant in Spectrocoin and everything worked for me. I'll think about how to catch your error.

I deploy litecart on linux(manjaro),and created a new merchant in Spectrocoin,the same error
![image](https://github.com/shurco/litecart/assets/134895892/d5cc8aec-104a-4d93-b76a-3fc2aba1d875)

```
{"level":"info","latency":"218.09µs","status":200,"method":"GET","url":"/api/cart/payment","time":"2023-11-29T21:43:37+08:00","message":"Success"}
{"level":"warn","latency":"1.521689ms","status":400,"method":"POST","url":"/cart/payment","time":"2023-11-29T21:43:38+08:00","message":"Client error"}
{"level":"info","latency":"346.462µs","status":200,"method":"GET","url":"/api/_/settings/spectrocoin","time":"2023-11-29T21:49:53+08:00","message":"Success"}
{"level":"warn","latency":"1.552585ms","status":400,"method":"POST","url":"/cart/payment","time":"2023-11-29T21:57:00+08:00","message":"Client error"}
```

**Comment by shurco** [comment]
Spectrocoin usually returns an error if it doesn't like the parameters, I'll try to add error output to the browser console. Maybe this will help.
I recently released a new version, maybe it will help.

**Comment by jiaotiliu** [comment]
> Spectrocoin usually returns an error if it doesn't like the parameters, I'll try to add error output to the browser console. Maybe this will help. I recently released a new version, maybe it will help.

I set the test products price up to $2 instead of $1,its work!

**Comment by shurco** [comment]
> > Spectrocoin usually returns an error if it doesn't like the parameters, I'll try to add error output to the browser console. Maybe this will help. I recently released a new version, maybe it will help.
> 
> I set the test products price up to $2 instead of $1,its work!(v1.0.7)

Strange. I tried to add a product costing 1 dollar and pay with crypto - everything works for me.
