### ISSUE TITLE
🐛 [Bug]: error 413 (Payload Too Large) for files over a megabyte

### ISSUE THREAD

**Issue by coderofsalvation** [shurco/litecart#81]
### Bug Description

When I'm uploading a file-asset over a megabyte, the server will fail silently with: `413 (Payload Too Large)` in the browser console

I guess I can just overwrite a small file with a bigger one (in the lc_digital) using scp e.g., but perhaps the upload-endpoint could accept a higher uploadsize.

### How to Reproduce

1. add a product
2. upload a digital file around 10 mb

### Expected Behavior

accept bigger file uploads 

### litecart Version

v0.1.9

### Checklist:

- [X] I agree to follow litecart's [Code of Conduct](https://github.com/shurco/litecart/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by shurco** [comment]
@coderofsalvation this update will be available in the next build

**Comment by coderofsalvation** [comment]
this is awesome news thx 🥳❤️
