### ISSUE TITLE
🐛 [Bug]: Cant add paymethod spectrocoin

### ISSUE THREAD

**Issue by jiaotiliu** [shurco/litecart#87]
### Bug Description

ERROR:

<html>
<body>

2024/01/09 11:10:40 | stdout | {"level":"warn","latency":"603.536µs","status":404,"method":"PATCH","url":"/api/_/settings","time":1704769840,"message":"Client error"}
-- | -- | --

</body>
</html>

![image](https://github.com/shurco/litecart/assets/134895892/8e93e40b-446b-4e69-9dfb-d10d64f2d907)

### How to Reproduce

 ADD NEW PAYMETHOD

### Expected Behavior

 NEW PAYMETHOD

### litecart Version

v0.1.9

### Code Snippet (optional)

```go
2024/01/09 11:10:40 | stdout | {"level":"warn","latency":"603.536µs","status":404,"method":"PATCH","url":"/api/_/settings","time":1704769840,"message":"Client error"}
-- | -- | --
```

### Checklist:

- [X] I agree to follow litecart's [Code of Conduct](https://github.com/shurco/litecart/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by shurco** [comment]
@jiaotiliu Did I understand you correctly - this error occurs when saving the SpectroCoin settings?

**Comment by jiaotiliu** [comment]
> @jiaotiliu Did I understand you correctly - this error occurs when saving the SpectroCoin settings?

yes
